import { topicTranslations, type Locale } from "./content/questions";
export type { Locale } from "./content/questions";

export const locales: Locale[] = ["ar", "en"];

export const messages = {
  ar: {
    submitDifficultyNone: "غير محدد", submitTrackPreference: "اختر مسارًا نشطًا من تفضيلات المسارات.",
    brandName: "تحضير المقابلات التقنية",
    home: "الرئيسية", topics: "الموضوعات", questions: "مكتبة الأسئلة", interview: "مقابلة كاملة", progress: "تقدمي", submit: "اقترح سؤالًا", moderator: "المراجعة", myTracks: "مساراتي", account: "الحساب",
    skip: "انتقل إلى المحتوى", menu: "القائمة", close: "إغلاق", theme: "تغيير المظهر", dark: "◐ الوضع الداكن", light: "☀ الوضع الفاتح", signIn: "تسجيل الدخول", signUp: "إنشاء حساب",
    libraryEyebrow: "مكتبة الأسئلة", libraryTitle: "مكتبة الأسئلة", libraryDescription: "راجع السؤال، جاوب بصوتك، وبعدها افتح التفاصيل وقارن إجابتك بشرح مدعوم بالمصدر الرسمي.",
    activeTrack: "المسار النشط", activeTrackLoading: "جاري تحميل المسار النشط…", activeTrackUnavailable: "تعذر تحميل المسار النشط", manageTrackPreferences: "إدارة تفضيلات المسارات", invalidTrackTitle: "المسار غير متاح", invalidTrackTopicTitle: "الموضوع لا ينتمي إلى هذا المسار", invalidTrackDescription: "غيّر المسار مع الحفاظ على سياق الصفحة، أو عدّل تفضيلات مساراتك.", changeTrackTo: "التغيير إلى", emptyTrackTitle: "لا يوجد محتوى في هذا المسار حاليًا", emptyTrackDescription: "المسار ما زال محددًا. اختر مسارًا آخر أو أدِر تفضيلاتك من غير تغيير صامت.",
    search: "ابحث في الأسئلة", searchPlaceholder: "مثال: final أو وقت التشغيل", topic: "الموضوع", allTopics: "كل الموضوعات", difficulty: "مستوى الصعوبة", allDifficulties: "كل المستويات", progressFilter: "حالة المراجعة", allProgress: "كل الحالات", favoriteOnly: "المفضلة فقط", available: "سؤال متاح.", startSession: "ابدأ جلسة المراجعة", prepareSession: "جهّز جلسة مراجعة", noResults: "مفيش نتائج مطابقة", expandFilters: "جرّب تغيّر البحث أو توسّع الفلاتر.",
    topicsEyebrow: "المسار النشط", topicsTitle: "الموضوعات", topicsDescription: "محتوى المسار النشط متقسم حسب المفاهيم اللي بتتقابل في الانترفيو.", availableQuestions: "سؤال متاح للمراجعة حاليًا.", viewQuestions: "عرض الأسئلة ←",
    homeEyebrow: "مسار Flutter متاح الآن", homeTitle: "ادخل الانترفيو وإجابتك مرتبة في دماغك.", homeLead: "أسئلة تقنية مختارة، إجابات عربية واضحة، ومراجع رسمية تساعدك تراجع المفهوم بدل ما تحفظ جملة.", startReview: "ابدأ المراجعة", exploreTopics: "استكشف الموضوعات", currentQuestions: "سؤال دائم في النسخة الأولى", firstTopic: "أول موضوع متاح ضمن مسار Flutter.", featuredTitle: "ابدأ بسؤال Dart", featuredLead: "إجابة قصيرة أولاً، ثم شرح أعمق ومصدر رسمي.", allQuestions: "كل الأسئلة", answerPrompt: "جاوب من ذاكرتك، وبعدها اكشف الإجابة وقارن شرحك بالتفاصيل.", readAnswer: "اقرأ الإجابة كاملة ←",
    sessionEyebrow: "جلسة مراجعة", sessionTitle: "جلسة مراجعة", sessionDescription: "اختار موضوعًا ومستوى، وراجع بالترتيب من غير مؤقت أو عشوائية.", chooseTopic: "اختار موضوعًا", chooseDifficulty: "اختار المستوى", preparing: "جاري تجهيز الجلسة...", question: "سؤال", of: "من", previous: "السؤال السابق", next: "السؤال التالي", noCombination: "لا توجد أسئلة للجمع ده", startStudy: "ابدأ جلسة مراجعة", selectSession: "اختار موضوعًا ومستوى من القوائم عشان نجهز لك الأسئلة بالترتيب.",
    interviewEyebrow: "مقابلة كاملة", interviewTitle: "ابنِ انترفيو شامل", interviewDescription: "اختار أكثر من موضوع من المسار النشط ومستوى واحد. المستوى الأعلى يشمل أسئلته وأسئلة المستويات الأقل.", chooseTopics: "اختار الموضوعات", selected: "مختارة", interviewLevel: "مستوى المقابلة", inclusiveHint: "المستوى المختار يشمل كل المستويات الأقل منه.", preparingInterview: "جاري تجهيز المقابلة...", completeSetup: "كمّل إعداد المقابلة", startInterview: "ابدأ مقابلة كاملة", interviewEmpty: "اختار موضوعًا واحدًا على الأقل ومستوى المقابلة عشان نجهز لك الأسئلة.",
    progressEyebrow: "تقدمك على الجهاز", progressTitle: "تقدمي", progressDescription: "حالتك محفوظة على الجهاز ده فقط، من غير حساب أو إرسال بيانات.", reviewed: "راجعت", continueReview: "كمّل المراجعة", reviewing: "قيد المراجعة", mastered: "متقن", favorites: "المفضلة", noQuestions: "لا توجد أسئلة هنا حاليًا.", resetTitle: "إعادة ضبط البيانات المحلية", resetDescription: "يمسح تقدم الأسئلة والمفضلة فقط.", reset: "إعادة ضبط التقدم", resetConfirm: "متأكد إنك عايز تمسح تقدمك والمفضلة من الجهاز ده؟",
    backLibrary: "← مكتبة الأسئلة", lastReviewed: "آخر مراجعة", staleReview: "راجع الإجابة من المصدر قبل الانترفيو لو مر وقت طويل على التاريخ ده.", progressLegend: "تقدم السؤال", favorite: "حفظ في المفضلة", saved: "تم حفظ التقدم على هذا الجهاز", reveal: "اكشف الإجابة", hide: "اخفِ الإجابة", shortAnswer: "الإجابة المختصرة", explanation: "الشرح", code: "مثال بالكود", mistakes: "أخطاء شائعة", followUps: "أسئلة متابعة", sources: "المصادر", notFound: "السؤال غير موجود", databaseQuestionEyebrow: "سؤال من قاعدة البيانات", databaseQuestionLoading: "جاري تحميل السؤال…", databaseQuestionNotFound: "تأكد من الرابط أو ارجع لمكتبة الأسئلة.", databaseQuestionError: "تعذر تحميل السؤال", databaseQuestionErrorDescription: "حصلت مشكلة مؤقتة في الاتصال. جرّب مرة أخرى.", databaseQuestionRetry: "إعادة المحاولة", footer: "محتوى عربي أصلي بمراجع رسمية.", language: "English",
    submitEyebrow: "مساهمة المجتمع", submitTitle: "اقترح سؤال مقابلة", submitDescription: "شارك سؤالًا وإجابة مفيدة. كل مساهمة تمر بمراجعة قبل ظهورها في المكتبة.", submitLoading: "جاري تحميل حالة الحساب…", submitSignInRequired: "سجّل الدخول لإرسال سؤال.", submitEmailRequired: "أكد بريدك الإلكتروني أولًا قبل إرسال المساهمات.", submitTrack: "المسار", submitTopics: "الموضوعات", submitQuestion: "السؤال", submitShortAnswer: "الإجابة المختصرة", submitExplanation: "الشرح", submitDifficulty: "مستوى الصعوبة", submitSources: "مصادر رسمية", submitSourcesHint: "رابط HTTPS واحد في كل سطر", submitCode: "مثال بالكود (اختياري)", submitMistakes: "أخطاء شائعة (اختياري، كل سطر نقطة)", submitFollowups: "أسئلة متابعة (اختياري، كل سطر سؤال)", submitDisplayName: "اسم العرض (اختياري)", submitConsent: "أوافق على نشر المساهمة بترخيص CC BY 4.0.", submitButton: "إرسال للمراجعة", submitSubmitting: "جاري الإرسال…", submitPending: "تم حفظ المساهمة وجاري إنشاء Issue للمراجعة…", submitSuccess: "تم إرسال المساهمة للمراجعة.", submitSuccessIssue: "فتح Issue على GitHub", submitDuplicate: "قد تكون مشابهة لسؤال موجود وسيُراجعها المشرف", submitFailed: "تعذر إنشاء Issue، يمكنك المحاولة مرة أخرى.", submitRetry: "إعادة المحاولة", submitRateLimit: "وصلت للحد اليومي (5 مساهمات).", submitCooldown: "انتظر دقيقة قبل إرسال مساهمة أخرى.", submitSuspended: "تم إيقاف حسابك مؤقتًا عن إرسال المساهمات.", submitValidation: "راجع الحقول المطلوبة، الروابط، والمحتوى قبل الإرسال.", submitUnavailable: "الخدمة غير متاحة حاليًا. حاول لاحقًا.", moderatorLoading: "جاري تحميل المساهمات…", moderatorSignIn: "سجّل الدخول للوصول إلى لوحة المراجعة.", moderatorStatus: "حالة المساهمات", moderatorRefresh: "تحديث", moderatorEmpty: "لا توجد مساهمات في هذه الحالة.", moderatorReason: "سبب القرار", moderatorChanges: "طلب تعديل", moderatorReject: "رفض المساهمة",
    onboardingEyebrow: "إعداد الحساب", onboardingTitle: "اختر مساراتك", onboardingDescription: "اختر مسارًا نشطًا واحدًا على الأقل وحدد المسار الافتراضي الذي تبدأ منه.", myTracksTitle: "مساراتي", myTracksDescription: "أضف أو احذف تفضيلات المسارات النشطة وغيّر المسار الافتراضي. لن يتأثر تقدم الأسئلة أو المفضلة أو المساهمات السابقة.", tracksLoading: "جاري تحميل المسارات…", tracksSignIn: "سجّل الدخول لإدارة مساراتك.", tracksAuthSetup: "إدارة المسارات تحتاج إعداد تسجيل الدخول أولًا.", tracksLegend: "تفضيلات المسارات", defaultTrackLegend: "المسار الافتراضي", defaultTrackHint: "يجب أن يكون المسار الافتراضي ضمن المسارات المختارة.", unavailableTracksLegend: "المسارات التاريخية غير المتاحة", trackUnavailable: "غير متاح", tracksRequired: "اختر مسارًا نشطًا واحدًا على الأقل.", defaultTrackRequired: "اختر مسارًا افتراضيًا من المسارات المختارة.", lastTrackRequired: "لا يمكن حذف آخر تفضيل مسار نشط.", tracksSave: "حفظ المسارات", tracksSaving: "جاري الحفظ…", tracksSaved: "تم حفظ تفضيلات المسارات والمسار الافتراضي.", tracksUnavailable: "تعذر تحميل أو حفظ تفضيلات المسارات. جرّب مرة أخرى.", tracksRetry: "إعادة المحاولة", tracksContinue: "متابعة", continueBrowsing: "متابعة تصفح المكتبة", noActiveTracksTitle: "لا توجد مسارات نشطة الآن", noActiveTracksDescription: "ارجع لاحقًا عندما يتوفر مسار نشط لإكمال الإعداد.", tracksRecoveryTitle: "المسارات المختارة لم تعد متاحة", tracksRecoveryDescription: "اختر مسارًا نشطًا جديدًا للعودة إلى الإعداد. بيانات تقدمك ومفضلاتك ومساهماتك السابقة محفوظة.", tracksRecoveryAction: "العودة إلى الإعداد",
  },
  en: {
    submitDifficultyNone: "Not specified", submitTrackPreference: "Choose one active Track Preference.",
    brandName: "Tech Interview Prep",
    home: "Home", topics: "Topics", questions: "Question Library", interview: "Full Interview", progress: "Progress", submit: "Suggest a question", moderator: "Moderation", myTracks: "My Tracks", account: "Account",
    skip: "Skip to content", menu: "Menu", close: "Close", theme: "Change theme", dark: "◐ Dark mode", light: "☀ Light mode", signIn: "Sign in", signUp: "Sign up",
    libraryEyebrow: "Question library", libraryTitle: "Question library", libraryDescription: "Answer out loud, open the details, and compare your reasoning with an answer backed by official sources.",
    activeTrack: "Active Track", activeTrackLoading: "Loading Active Track…", activeTrackUnavailable: "Active Track could not be loaded", manageTrackPreferences: "Manage Track Preferences", invalidTrackTitle: "This Track is unavailable", invalidTrackTopicTitle: "This Topic does not belong to the Active Track", invalidTrackDescription: "Change Track while keeping this page context, or manage your Track Preferences.", changeTrackTo: "Change to", emptyTrackTitle: "This Track has no content yet", emptyTrackDescription: "The Track remains selected. Choose another Track or manage preferences without a silent switch.",
    search: "Search questions", searchPlaceholder: "Example: final or runtime", topic: "Topic", allTopics: "All topics", difficulty: "Difficulty", allDifficulties: "All levels", progressFilter: "Question progress", allProgress: "All progress", favoriteOnly: "Favorites only", available: "questions available.", startSession: "Start review session", prepareSession: "Prepare a review session", noResults: "No matching results", expandFilters: "Try changing the search or widening the filters.",
    topicsEyebrow: "Active Track", topicsTitle: "Topics", topicsDescription: "Browse the interview concepts in the Active Track.", availableQuestions: "questions currently available for review.", viewQuestions: "View questions →",
    homeEyebrow: "Flutter track is ready", homeTitle: "Walk into the interview with your answers organized.", homeLead: "Curated technical questions, clear explanations, and official references that help you understand instead of memorizing.", startReview: "Start reviewing", exploreTopics: "Explore topics", currentQuestions: "questions in the first release", firstTopic: "First topic in the Flutter track.", featuredTitle: "Start with a Dart question", featuredLead: "A short answer first, then a deeper explanation and an official source.", allQuestions: "All questions", answerPrompt: "Answer from memory, then reveal the explanation and compare your reasoning.", readAnswer: "Read the full answer →",
    sessionEyebrow: "Review session", sessionTitle: "Review session", sessionDescription: "Choose a topic and level, then review in order without a timer or randomization.", chooseTopic: "Choose a topic", chooseDifficulty: "Choose a level", preparing: "Preparing the session…", question: "Question", of: "of", previous: "Previous question", next: "Next question", noCombination: "No questions match this combination", startStudy: "Start a review session", selectSession: "Choose a topic and level to prepare the questions in order.",
    interviewEyebrow: "Full interview", interviewTitle: "Build a complete interview", interviewDescription: "Choose multiple Topics in the Active Track and one level. A higher level includes its own questions and all lower levels.", chooseTopics: "Choose topics", selected: "selected", interviewLevel: "Interview level", inclusiveHint: "The selected level includes every lower level.", preparingInterview: "Preparing the interview…", completeSetup: "Finish setting up the interview", startInterview: "Start full interview", interviewEmpty: "Choose at least one topic and an interview level to prepare your questions.",
    progressEyebrow: "Your progress on this device", progressTitle: "Progress", progressDescription: "Your state is stored on this device only. No account or data upload is required.", reviewed: "Reviewed", continueReview: "Continue reviewing", reviewing: "Reviewing", mastered: "Mastered", favorites: "Favorites", noQuestions: "No questions here yet.", resetTitle: "Reset local data", resetDescription: "Clears question progress and favorites only.", reset: "Reset progress", resetConfirm: "Are you sure you want to clear progress and favorites on this device?",
    backLibrary: "← Question library", lastReviewed: "Last reviewed", staleReview: "Check the source before your interview if this review date is old.", progressLegend: "Question progress", favorite: "Save to favorites", saved: "Progress saved on this device", reveal: "Reveal answer", hide: "Hide answer", shortAnswer: "Short answer", explanation: "Explanation", code: "Code example", mistakes: "Common mistakes", followUps: "Follow-up questions", sources: "Sources", notFound: "Question not found", databaseQuestionEyebrow: "Database question", databaseQuestionLoading: "Loading question…", databaseQuestionNotFound: "Check the link or return to the question library.", databaseQuestionError: "Could not load the question", databaseQuestionErrorDescription: "There was a temporary connection problem. Try again.", databaseQuestionRetry: "Retry", footer: "Original content with official references.", language: "العربية",
    submitEyebrow: "Community contribution", submitTitle: "Suggest an interview question", submitDescription: "Share a useful question and answer. Every contribution is reviewed before it appears in the library.", submitLoading: "Loading account status…", submitSignInRequired: "Sign in to submit a question.", submitEmailRequired: "Confirm your email before submitting a contribution.", submitTrack: "Track", submitTopics: "Topics", submitQuestion: "Question", submitShortAnswer: "Short answer", submitExplanation: "Explanation", submitDifficulty: "Difficulty", submitSources: "Official sources", submitSourcesHint: "One HTTPS URL per line", submitCode: "Code example (optional)", submitMistakes: "Common mistakes (optional, one per line)", submitFollowups: "Follow-up questions (optional, one per line)", submitDisplayName: "Display name (optional)", submitConsent: "I agree to publish this contribution under CC BY 4.0.", submitButton: "Submit for review", submitSubmitting: "Submitting…", submitPending: "Contribution saved; creating the review Issue…", submitSuccess: "Contribution submitted for review.", submitSuccessIssue: "Open GitHub Issue", submitDuplicate: "It may resemble an existing question and will be reviewed", submitFailed: "The review Issue could not be created.", submitRetry: "Retry", submitRateLimit: "Daily limit reached (5 submissions).", submitCooldown: "Wait a minute before sending another contribution.", submitSuspended: "Your account is suspended from submitting contributions.", submitValidation: "Check required fields, links, and content before submitting.", submitUnavailable: "The service is currently unavailable. Try again later.", moderatorLoading: "Loading submissions…", moderatorSignIn: "Sign in to access the moderator console.", moderatorStatus: "Submission status", moderatorRefresh: "Refresh", moderatorEmpty: "No submissions match this status.", moderatorReason: "Decision reason", moderatorChanges: "Request changes", moderatorReject: "Reject submission",
    onboardingEyebrow: "Account setup", onboardingTitle: "Choose your Tracks", onboardingDescription: "Select at least one active Track and choose the Default Track you want to start from.", myTracksTitle: "My Tracks", myTracksDescription: "Add or remove active Track Preferences and change your Default Track. Question Progress, Favorites, and historical Submissions stay untouched.", tracksLoading: "Loading Tracks…", tracksSignIn: "Sign in to manage your Tracks.", tracksAuthSetup: "Track management requires authentication setup first.", tracksLegend: "Track Preferences", defaultTrackLegend: "Default Track", defaultTrackHint: "Your Default Track must be one of your selected Tracks.", unavailableTracksLegend: "Unavailable historical Tracks", trackUnavailable: "Unavailable", tracksRequired: "Select at least one active Track.", defaultTrackRequired: "Choose a Default Track from your selected Tracks.", lastTrackRequired: "You cannot remove the last active Track Preference.", tracksSave: "Save Tracks", tracksSaving: "Saving…", tracksSaved: "Your Track Preferences and Default Track were saved.", tracksUnavailable: "Track Preferences could not be loaded or saved. Try again.", tracksRetry: "Retry", tracksContinue: "Continue", continueBrowsing: "Continue browsing the catalogue", noActiveTracksTitle: "No active Tracks are available", noActiveTracksDescription: "Come back when an active Track is available to finish setup.", tracksRecoveryTitle: "Your selected Tracks are no longer available", tracksRecoveryDescription: "Choose a new active Track to return to Onboarding. Your Question Progress, Favorites, and historical Submissions are preserved.", tracksRecoveryAction: "Return to Onboarding",
  },
} as const;

export function localeFromPathname(pathname: string): Locale {
  return pathname.split("/").filter(Boolean).find((segment) => segment === "en" || segment === "ar") === "en" ? "en" : "ar";
}

export function localizedHref(locale: Locale, path = "/"): string {
  const normalized = path.startsWith("/") ? path : `/${path}`;
  return `/${locale}${normalized === "/" ? "/" : normalized}`;
}

export function localeDirection(locale: Locale): "rtl" | "ltr" {
  return locale === "ar" ? "rtl" : "ltr";
}

export function topicName(locale: Locale, topicId: string): string {
  return topicTranslations[locale][topicId] ?? topicId;
}

export function formatNumber(value: number, locale: Locale): string {
  return new Intl.NumberFormat(locale === "ar" ? "ar-EG" : "en-US").format(value);
}

export function formatDate(value: string, locale: Locale): string {
  return new Intl.DateTimeFormat(locale === "ar" ? "ar-EG" : "en-US", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00Z`));
}
